{{- if and .Values.gateway.enabled $.Values.oauth2Proxy.providers }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  hostnames:
  {{- range .Values.gateway.hosts }}
  - {{ . }}
  {{- end }}
  parentRefs:
  - name: giantswarm-default
    namespace: envoy-gateway-system
  rules:
  {{- range $provider := $.Values.oauth2Proxy.providers }}
  - backendRefs:
    - name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
      port: {{ $.Values.port.port }}
    matches:
    - path:
        type: PathPrefix
        value: /oauth2/{{ $provider.id }}(/|$)(.*)
  {{- end }}
{{- end }}
