{{- if .Values.route.enabled -}}
{{- $route := .Values.route }}
apiVersion: gateway.networking.k8s.io/v1
kind: {{ $route.kind | default "HTTPRoute" }}
metadata:
  name: {{ $route.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- if $route.additionalRules }}
    {{- tpl (toYaml $route.additionalRules) $ | nindent 4 }}
    {{- end }}
    {{- range $provider := $.Values.oauth2Proxy.providers }}
    - backendRefs:
        - name: {{ include "resource.default.name" $ }}-{{ $provider.id }}
          port: {{ $.Values.port.port }}
      matches:
      - path:
          type: PathPrefix
          value: /oauth2/{{ $provider.id }}(/|$)(.*)
    {{- end }}
{{- end }}
